# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd55a8a4241be917fa69ada4c8807a8b23d5ab91f8ca7d8dcc9c458dc6c898593b56186c7000b86f073f27e9ae56300bf5d0429477037cf24cd02e6ee13c6048

test:
  secret_key_base: cba83411448c214f1ed39b806bdde015f8b7f1c832cf09492c07166f2d7437f6fd125e18e23d1b733fe045cd65d280555cc55bff5b4e2dba9069ce0b9320b9d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
